version = 1

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
    environment = ["browser", "node"]
    plugins = ["react"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "docker"
enabled = true
