sonar.projectKey=heitorpolidoro_repertoire-hero
sonar.organization=heitorpolidoro
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,.next/**,coverage/**
sonar.coverage.exclusions=src/app/**
