name: "Node.js CI"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    uses: heitorpolidoro/.github/.github/workflows/node-ci.yml@master
    with:
      node-versions: "['24.x']"
      sonar-node-version: "24.x"
      database: supabase
    secrets: inherit # pragma: allowlist secret
